### ISSUE TITLE
overriding timestamps is usually incorrect

### ISSUE THREAD

**Issue by cboulay** [labstreaminglayer/App-PupilLabs#4] opened 2019-04-08 04:24 UTC
@papr , I know you are aware of this problem but I think the current method is incorrect because if something else affects Capture's timebase ([e.g. hmd-eyes](https://github.com/pupil-labs/pupil/issues/1449)) then the pupil LSL stream is useless as it cannot be synchronized with other streams.

I think the LSL team needs to do a better job communicating how 'sacred' the LSL timestamps are. The only instances where overriding LSL timestamps is really warranted is when the outlet gets the _lsl_ clock when the samples are acquired from the device, but then there's some processing etc after acquiring the samples which adds some delay so it is better to use the lsl-time-at-acquisition instead of the default lsl-time-at-push.

If you want to make use of timestamps provided by the device directly or some other clock then the better way to do that is to add a channel to your stream containing the timestamps.

**Comment by papr** [comment] 2019-04-08 12:12
I understand that the Pupil time needs to stay in sync with the `pylsl.local_clock()` in order to function as a valid clock for LSL. That is why I added the warning in the README "LSL Clock Synchronization" section.

I find it less than optimal to add the Pupil time timestamps as an additional channel since it requires users to manually adjust them during post-processing instead of using LSL's built-in synchronization. Also, the current LSL Relay implementation allows us to calculate `lsl-time-at-acquisition` which is nice for more precise correlation with other data sources.

The actual issue is that Capture allows multiple sources to modify the time epoch. This needs to change. Additionally, I have spoken to @fx-lange and we will implement a time-follower mode into the hmd-eyes project (as an alternative to the current time-setter/master mode).

**Comment by cboulay** [comment] 2019-04-08 12:19
Great. Do you know the timeline on that? because in its current state the plugin creates useless data.

**Comment by papr** [comment] 2019-04-08 12:38
There is no official timeline yet and it would be an alpha-release-only feature. Would it help if I added the `lsl-time-at-push` as an additional channel (while keeping `Pupil-time` as lsl timestamps which is equal to `lsl-time-at-acquisition` if there is no other clock manipulation)?

**Comment by cboulay** [comment] 2019-04-08 14:11
No that wouldn't help. The problem is that the file importers try to synchronize the different streams using their timestamps and clock offsets (which the library gets behind the scenes), but this is impossible when the timestamps and clock offsets are on different bases. Without the lsl timestamps being on the same base as the clock offsets, I would have to hack together some custom file importer that synchronizes other streams but not this stream, and then implement some other correction for pupil only. This kind of defeats the whole purpose of LSL.

**Comment by cboulay** [comment] 2019-04-08 20:28
@fx-lange - please let me know if there's something I can do to help move this along. I can code in Unity, I have a pupil debug environment working, etc., Please just give me some hints as to the important bits of code to look at. I need this fixed before I collect more data.

I'd rather not go back to the old plugin as it had its own issues and and work spent solving those issues will be obsolete as soon as the new plugin is fixed.

**Comment by cboulay** [comment] 2019-04-17 21:34
We've been playing around with the latest hmd-eyes which includes a change to not overwrite the pupil clock and instead have Unity timestamp its events using a pupil-like clock. That's great!

In my recorded XDF, the pupil timestamps are not monotonically increasing. This can be dealt with, but I just wanted to check to see if this was expected behaviour. Is it expected that a call to `recent_events` might get passed "gaze" events with a timestamp earlier than a previous call?

**Comment by papr** [comment] 2019-04-17 22:11
No, this is not expected behavior :thinking: Could you please check if these cases are low confidence monocular samples?

**Comment by cboulay** [comment] 2019-04-18 14:53
Yes, it seems it happens whenever there is a transition from a sample where all channels for eye_center0_3d_x, _y, _z and eye_center1_3d_x, _y, _z have data, to samples where one of those sets of 3 is nan.

It doesn't seem to have anything to do with confidence. Sometimes the monocular data has higher confidence than the binocular data.

**Comment by papr** [comment] 2019-06-10 09:21
The original issue has been fixed in https://github.com/pupil-labs/hmd-eyes/releases/tag/v1.0-beta
The negative time jump issue will be tracked in https://github.com/pupil-labs/pupil/issues/1493

**Closed as completed by papr** 2019-06-10 09:21 UTC
